# Generated by Django 6.1.1 on 2026-10-08 07:39

import cmms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0063_checklisttemplate_replaced_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_list',
            name='equipment_image',
            field=models.FileField(blank=True, upload_to=cmms.models.equipment_image_upload_path),
        ),
    ]
