# Generated by Django 6.1.1 on 2026-10-09 02:30

import cmms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0064_equipment_list_equipment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProfileFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('image', 'รูปภาพ'), ('document', 'เอกสาร/คู่มือ')], max_length=12)),
                ('file', models.FileField(upload_to=cmms.models.equipment_profile_file_upload_path)),
                ('display_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_files', to='cmms.equipment_list')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
