# Generated by Django 6.1.1 on 2026-10-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0065_equipmentprofilefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentprofilefile',
            name='uploaded_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
