# Generated by Django 6.1.1 on 2026-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0066_equipmentprofilefile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenthistory',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'สร้างทะเบียน'), ('UPDATE', 'แก้ไขทะเบียน'), ('DELETE', 'ลบทะเบียน'), ('FILE_UPLOAD', 'อัปโหลดไฟล์')], max_length=20, verbose_name='ประเภทการดำเนินการ'),
        ),
    ]
